
server:
  port: 8999
#  compression:
#    enabled: true
#    mime-types:
#      - application/octet-stream

spring:
  mvc:
    static-path-pattern: /static/**
  jmx:
    enabled: true

  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html; charset=utf-8